Catalyst/Models/AModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;

namespace Catalyst.Models
{
	/// <summary>
	/// Default implementation of IModel
	/// </summary>
	public abstract class AModel
		: IModel
	{
		/// members 

		public long id { get; set; } //todo: consider leaving out id, as it must often be attributed in derived classes
		public long created { get; set; }
		public long modified { get; set; }



		/// c/d'tors

		public AModel()
		{
		}



		/// public methods (e.g. facade syntatic sugar)

		abstract public bool Validate();

		/// <summary>
		/// Get key/value pairs of data.  (Example of common model helper method)
		/// </summary>
		/// <returns>key/value Dictionary</returns>
		public Dictionary<string, string>
		ToDictionary()
		{
			var ret = new Dictionary<string, string>();
			var props = this.GetType().GetProperties(BindingFlags.Instance | BindingFlags.Public);

			foreach (var info in props)
			{
				var value = info.GetValue(this, null);
				ret.Add(info.Name, (value == null) ? null: value.ToString());
			}

			return ret;
		}

		//FromDictionary, etc...
	}
}

Catalyst/Models/IModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Catalyst.Models
{
	public interface IModel
	{
		/// interface members 

		long id { get; set; }
		long created { get; set; }
		long modified { get; set; }



		/// interface methods (e.g. facade syntatic sugar, helper methods)

		//example
		bool Validate();

		//example
		Dictionary<string, string> ToDictionary();

		//etc...
	}
}

Catalyst/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Catalyst.Models
{
	public class Person 
		: AModel
	{
		/// members 

		//todo: set field lengths, required, etc
		public string firstName { get; set; } = "";
		public string lastName { get; set; } = "";
		public long birthDate { get; set; }
		public string interest { get; set; } = ""; //note: in a full db, this could be normalized to its own model & relation
		public string address { get; set; } = ""; //note: in a full db, this could be normalized to its own model & relation



		/// relations

		public virtual Picture picture { get; set; }
		public long pictureId { get; set; }



		/// interface (AModel)

		public override bool Validate()
		{
			throw new NotImplementedException();
		}

	}
}

Catalyst/Models/Picture.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Catalyst.Models
{
	public class Picture : AModel
	{
		/// members 

		//todo: set field lengths, required, etc
		[Key]
		[ForeignKey("person")]
		public new long id {
			get { return base.id; }
			set { base.id = value; } }
		public string mimeType { get; set; } = "";
		public long size { get; set; }
		public string path { get; set; } = ""; //[string path] or [byte[] data], but not both
		//public Byte[] data { get; set; }



		/// relations

		public virtual Person person { get; set; }
		public long personId { get; set; }



		/// interface (AModel)

		public override bool Validate()
		{
			throw new NotImplementedException();
		}
	}
}

Catalyst/Models/View/ViewSearch.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Catalyst.Models.View
{
	/// <summary>
	/// View model for handling search requests
	/// </summary>
	[Serializable]
	[JsonObject]
	public class ViewSearch
	{
		public string q { get; set; } = "";
		public long min { get; set; }
		public long max { get; set; }
	}
}

Catalyst/Controllers/ApiController.cs
using Catalyst.Db;
using Catalyst.Models.View;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Catalyst.Controllers
{
	/// <summary>
	///   API actions.  This could be a facade for deeper API's, or else you could break this
	///   into a folder and create its own model-based RESTful API.
	/// </summary>
	[OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
	public class ApiController 
		: Controller
    {
		/// members

		protected DbContext db = new CatalystContext(); //or DI



		/// actions

		// GET: Api
		//todo: use custom Result so data format can be configured, e.g. JSON/XML
		public JsonResult
		Index()
        {
			//disable circular references
			this.db.Configuration.LazyLoadingEnabled = false;
			this.db.Configuration.ProxyCreationEnabled = false;

			var repo = new ServicePerson(this.db);

			//default is to get everything
			//todo: add paging
			var data = repo.ReadAll();

			//simulate db delay
			System.Threading.Thread.Sleep(5000);

			return this.Json(data, JsonRequestBehavior.AllowGet);
        }


		// Post: Api/Search [ViewSearch]
		//todo: use custom Result so data format can be configured, e.g. JSON/XML
		[HttpPost]
		public JsonResult
		Search(
			ViewSearch search)
        {
			//disable circular references
			this.db.Configuration.LazyLoadingEnabled = false;
			this.db.Configuration.ProxyCreationEnabled = false;

			var repo = new ServicePerson(this.db);

			//todo: nonce xss check
			//todo: sanitize search.q
			if (search.q == null)
				search.q = "";

			//todo: add paging
			//search
			var data = repo.FindAllQueryByName(search.q)
				.Include(p => p.picture) //include pictures
				.ToList();

			//manual circular reference fix; todo: view models could fix this and protect re-serialization of EF models
			foreach (var p in data)
				if (p.picture != null)
					p.picture.person = null;

			//simulate db delay
			System.Threading.Thread.Sleep(4000);

			return this.Json(data, JsonRequestBehavior.AllowGet);
        }

    }
}

Catalyst/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Catalyst.Controllers
{
    public class IndexController 
		: Controller
    {
        public ActionResult 
		Index()
        {
			ViewBag.Message = "Index page.";
			return View();
        }
    }
}

Catalyst/Views/Index/Index.cshtml
@{
	ViewBag.Title = "Home Page";
}

@* todo: make separate template js file *@
<script type="text/x-kendo-template" id="contact-template">
	<section class="contact col-lg-5 col-sm-12">
        <div class="row">
            <div class="col-lg-3">
                <img class="contact-photo img-responsive" src="#: picture.path #" alt="#:firstName# #:lastName#" />
            </div>
            <div class="col-lg-5">
                <h3 class="contact-title">#:firstName# #:lastName#</h3>
                <p class="contact-address">#:address#</p>
                <p class="contact-age">Age: #: age #</p>
                <p class="contact-interest">Likes: #:interest#</p>
            </div>
        </div>
	</section>
</script>

<!--
<div class="jumbotron">
	<h1>Contact List</h1>
	<p class="lead">Find your star employees here!</p>
</div>
-->

<div class="row clearfix">
	<div class="well group-contact">
		<div class="group-contact-search">
			<input id="c-search-in" name="c-search-in" class="k-textbox" type="search" maxlength="40" placeholder="search..." />
			<input id="c-search-go" type="button" class="k-button" value="Go" />@* todo: icon instead of text *@
		</div>
		<div id="c-contacts" class="group-contact-contacts">
            <div class="contact-load">Loading...</div>
        </div>

		@* todo: move to own javascript file so CSP can be enabled *@
		<script>
			$(function () {
				var dataSource = new kendo.data.DataSource({
				    transport: {
				        read: {
				            url: "/api/search",
				            type: "post",
				            contentType: 'application/json; charset=utf-8',
				            dataType: "json",
				            //todo: error handler
				        },
				        parameterMap: function (data, type) {
				            return JSON.stringify({
                                q: $("#c-search-in").val(),
                                min: 0, //todo: paging
                                max: 0
				            });
				        }
				    },
					schema: {
						//add pre-calculated field for age
						parse: function (response) {
							var n = response.length,
								now = new Date(),
								dob,
								value;

							for (var i = 0; i < n; i++) {
							    value = response[i];
							    if (value.birthDate && (dob = new Date(value.birthDate))) {
							        value.age = now.getFullYear() - dob.getFullYear();
							        if (now.getMonth() < dob.getMonth() || now.getMonth() == dob.getMonth() && now.getDate() < dob.getDate())
							            value.age--;
                                }
							}

							return response;
						}
					}
				});

				$("#c-contacts").kendoListView({
				    dataSource: dataSource,
				    dataBound: function (e) {
				        if (this.dataSource.data().length == 0) {
				            $("#c-contacts").append('<div class="contact-load">No results</div>');
				        }
				    },
					template: kendo.template($("#contact-template").html())
				});

				@* todo: could trigger input box on change timer instead of button *@
				$('#c-search-go').click(function () {
					dataSource.read();
				});
			});
		</script>
	</div>
</div>

Catalyst/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Contact List</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @* todo: bundle kendo and add local *@
    <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.1.408/styles/kendo.common-bootstrap.min.css" />
    <link rel="stylesheet" href="http://cdn.kendostatic.com/2015.1.408/styles/kendo.bootstrap.min.css" />
    <script src="http://cdn.kendostatic.com/2015.1.408/js/kendo.all.min.js"></script>
    <script src="http://cdn.kendostatic.com/2015.1.408/js/kendo.timezones.min.js"></script>
    <script src="http://cdn.kendostatic.com/2015.1.408/js/kendo.aspnetmvc.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Catalyst", "Index", "Index", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Index")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 Dream Shard LLC</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>